<?php

namespace App\Exports;

use App\Models\Alumni;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;

class UserExports implements FromArray, WithHeadings
{
    public function array():array
    {
        $users = DB::select('SELECT
	U.NAME,
	U.EMAIL,
	U.USERNAME,
	U.PHONE_NUMBER,
	U.ROLE,
	A.PRODI,
	A.JENJANG,
	A.JENIS_KELAMIN,
	A.AGAMA,
	A.TAHUN_MASUK,
	A.TAHUN_LULUS,
	K.ALUMNI_STATUS,
	K.UNIVERSITY_PAYMENT_SOURCE,
	K.LECTURE_METHOD,
	K.DEMO_METHOD,
	K.PROJECT_METHOD,
	K.INTERNSHIP_METHOD,
	K.PRACTICAL_METHOD,
	K.FIELD_METHOD,
	K.DISCUSSION_METHOD,
	KW.JOB_POSITION,
	KW.JOB_BEFORE_STATUS,
	KW.JOB_ACQUIRED_TIME,
	KW.COMPANY,
	KW.SALARY,
	KW.COMPANY_PROVINCE,
	KW.COMPANY_REGENCY,
	KW.COMPANY_TYPE,
	KW.COMPANY_LEVEL,
	KW.UNIVERSITY_COMPANY_RELATION,
	KW.UNIVERSITY_COMPANY_LEVEL,
	KW.APPLIED_COMPANY,
	KW.APPLIED_COMPANY_RESPONDED,
	KW.APPLIED_COMPANY_INTERVIEWED,
	KW.JOB_HUNTING_STATUS,
	KW.JOB_HUNT_TYPE,
	KW.JOB_HUNT_MONTH,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.ETHICS
		END
	) AS GRAD_ETHICS,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.EXPERTISE
		END
	) AS GRAD_EXPERTISE,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.ENGLISH
		END
	) AS GRAD_ENGLISH,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.TECH
		END
	) AS GRAD_TECH,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.COMMUNICATION
		END
	) AS GRAD_COMMUNICATION,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.TEAMWORK
		END
	) AS GRAD_TEAMWORK,
	MAX(
		CASE
			WHEN KC.TYPE = "GRADUATION" THEN KC.DEVELOPMENT
		END
	) AS GRAD_DEVELOPMENT,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.ETHICS
		END
	) AS WORK_ETHICS,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.EXPERTISE
		END
	) AS WORK_EXPERTISE,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.ENGLISH
		END
	) AS WORK_ENGLISH,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.TECH
		END
	) AS WORK_TECH,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.COMMUNICATION
		END
	) AS WORK_COMMUNICATION,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.TEAMWORK
		END
	) AS WORK_TEAMWORK,
	MAX(
		CASE
			WHEN KC.TYPE = "WORK" THEN KC.DEVELOPMENT
		END
	) AS WORK_DEVELOPMENT,
	GROUP_CONCAT(KWH.JOB_HUNT_METHOD) AS JOB_HUNT,
	GROUP_CONCAT(KWH.REMARKS) AS JOB_HUNT_REMARKS,
	GROUP_CONCAT(KWC.COMPATIBILITY_TYPE) AS COMPATIBILITY,
	GROUP_CONCAT(KWC.COMPATIBILITY) AS COMPATIBILITY_REMARKS,
	KE.LOCATION,
	KE.PAYMENT_TYPE,
	KE.START_DATE,
	KE.UNIVERSITY_NAME,
	KE.MAJOR,
	KE.REASONS
FROM
	USERS U
	LEFT JOIN ALUMNIS A ON A.USER_ID = U.ID
	LEFT JOIN KUESIONER K ON K.ALUMNI_ID = A.ID
	LEFT JOIN KUESIONER_WORK KW ON KW.TRACER_STUDY_ID = K.ID
	LEFT JOIN KUESIONER_COMPETENCY KC ON KC.KUESIONER_WORK_ID = KW.ID
	LEFT JOIN KUESIONER_WORK_HUNT KWH ON KWH.KUESIONER_WORK_ID = KW.ID
	LEFT JOIN KUESIONER_WORK_COMPATIBILITY KWC ON KWC.KUESIONER_WORK_ID = KW.ID
	LEFT JOIN KUESIONER_EDUCATION KE ON KE.TRACER_STUDY_ID = K.ID
WHERE
	U.ROLE = "Alumni"
GROUP BY
	U.NAME,
	U.EMAIL,
	U.USERNAME,
	U.PHONE_NUMBER,
	U.ROLE,
	A.PRODI,
	A.JENJANG,
	A.JENIS_KELAMIN,
	A.AGAMA,
	A.TAHUN_MASUK,
	A.TAHUN_LULUS,
	K.ALUMNI_STATUS,
	K.UNIVERSITY_PAYMENT_SOURCE,
	K.LECTURE_METHOD,
	K.DEMO_METHOD,
	K.PROJECT_METHOD,
	K.INTERNSHIP_METHOD,
	K.PRACTICAL_METHOD,
	K.FIELD_METHOD,
	K.DISCUSSION_METHOD,
	KW.JOB_POSITION,
	KW.JOB_BEFORE_STATUS,
	KW.JOB_ACQUIRED_TIME,
	KW.COMPANY,
	KW.SALARY,
	KW.COMPANY_PROVINCE,
	KW.COMPANY_REGENCY,
	KW.COMPANY_TYPE,
	KW.COMPANY_LEVEL,
	KW.UNIVERSITY_COMPANY_RELATION,
	KW.UNIVERSITY_COMPANY_LEVEL,
	KW.APPLIED_COMPANY,
	KW.APPLIED_COMPANY_RESPONDED,
	KW.APPLIED_COMPANY_INTERVIEWED,
	KW.JOB_HUNTING_STATUS,
	KW.JOB_HUNT_TYPE,
	KW.JOB_HUNT_MONTH,
	KE.LOCATION,
	KE.PAYMENT_TYPE,
	KE.START_DATE,
	KE.UNIVERSITY_NAME,
	KE.MAJOR,
	KE.REASONS,
	K.ID;');

        $indexedUsers = array_map(function ($user, $index) {
            $userArray = (array) $user;
            $userArray = ['INDEX' => $index + 1] + $userArray;
            return (object) $userArray;
        }, $users, array_keys($users));

        return $indexedUsers;
    }

    public function headings(): array
    {
        return [
            "NO.",
            "NAME",
            "EMAIL",
            "USERNAME",
            "PHONE_NUMBER",
            "ROLE",
            "PRODI",
            "JENJANG",
            "JENIS_KELAMIN",
            "AGAMA",
            "TAHUN_MASUK",
            "TAHUN_LULUS",
            "ALUMNI_STATUS",
            "UNIVERSITY_PAYMENT_SOURCE",
            "LECTURE_METHOD",
            "DEMO_METHOD",
            "PROJECT_METHOD",
            "INTERNSHIP_METHOD",
            "PRACTICAL_METHOD",
            "FIELD_METHOD",
            "DISCUSSION_METHOD",
            "JOB_POSITION",
            "JOB_BEFORE_STATUS",
            "JOB_ACQUIRED_TIME",
            "COMPANY",
            "SALARY",
            "COMPANY_PROVINCE",
            "COMPANY_REGENCY",
            "COMPANY_TYPE",
            "COMPANY_LEVEL",
            "UNIVERSITY_COMPANY_RELATION",
            "UNIVERSITY_COMPANY_LEVEL",
            "APPLIED_COMPANY",
            "APPLIED_COMPANY_RESPONDED",
            "APPLIED_COMPANY_INTERVIEWED",
            "JOB_HUNTING_STATUS",
            "JOB_HUNT_TYPE",
            "JOB_HUNT_MONTH",
            "GRAD_ETHICS",
            "GRAD_EXPERTISE",
            "GRAD_ENGLISH",
            "GRAD_TECH",
            "GRAD_COMMUNICATION",
            "GRAD_TEAMWORK",
            "GRAD_DEVELOPMENT",
            "WORK_ETHICS",
            "WORK_EXPERTISE",
            "WORK_ENGLISH",
            "WORK_TECH",
            "WORK_COMMUNICATION",
            "WORK_TEAMWORK",
            "WORK_DEVELOPMENT",
            "JOB_HUNT",
            "JOB_HUNT_REMARKS",
            "COMPATIBILITY",
            "COMPATIBILITY_REMARKS",
            "LOCATION",
            "PAYMENT_TYPE",
            "START_DATE",
            "UNIVERSITY_NAME",
            "MAJOR",
            "REASONS"
        ];
    }
}
